
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Festival.sln'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    publishTestResults: true
    projects: '**/*.Tests.csproj'
